### ISSUE TITLE
license (and possibly credits) missing for affirmative.mp3 and ready.mp3

### ISSUE THREAD

**Issue by qubodup** [cxong/BlueAlert#7]
https://opengameart.org/content/sci-fi-rts-war-unit-sounds is gpl2, 3 or ccbysa3.

I can't find mention of either license or credits though.

**Comment by cxong** [comment]
They are mentioned in `units.txt`

**Comment by qubodup** [comment]
Thanks! It's unclear which files are affected however. I can try to create a pull request to fix that. Would you prefer one txt file per file (affirmative.txt, bg.txt, building.txt etc) or one license.txt file that holds info on all files?

Under GPL my files don't require attribution but some files require attribution (explode, m16, music). Yet there are no credits on https://congusbongus.itch.io/blue-alert . Would you like me to prepare a formatted text block to include credits/license info on that page? (easier than adding a credits view in-game I imagine).

**Comment by cxong** [comment]
Yes, that sounds great. Either approach for the license files is fine.

**Comment by qubodup** [comment]
After *only* 5 years… The sound pack is now CC0.

As for consolidated credits, which could be used on the itch page and/or in the README:

## Credits

### Code, Design
congusbongus [or perhaps use "full name (nickname)"]

### Audio

Agony: Agony (https://freesound.org/s/162157/ CC0)  
Mediapaja2009

Browning: Air Defense Artillery Avenger Training .50cal (tH4YBTw8vk8).flac (http://freesound.org/s/160355/ CC0)  
Tank Fire: Tank Firing (http://freesound.org/s/168707/ CC0)  
Units (http://opengameart.org/content/sci-fi-rts-war-unit-sounds CC0)  
qubodup

Explode: Various C64 Sid Chip Sound Effects (http://opengameart.org/content/various-c64-sid-chip-sound-effects CC BY-SA 3.0)  
Panayiotis Yianni (Amon)

M16: M-16 automatic gun (http://freesound.org/people/Julien%20Nicolas/sounds/133799/ CC BY 3.0)  
Julien Nicolas

Music: Crystalline Refinement (Into This Wired Abyss Vol. 3) (http://www.ektoplazm.com/free-music/into-this-wired-abyss-vol-3 CC BY-NC-SA 4.0)  
False Identity

Speech: RTS commands and reports (http://opengameart.org/content/rts-commands-and-reports CC0)  
Daniel Stephens (Scribe)

### Font

Boxy Bold Regular 12: Boxy Bold - TrueType Font (http://opengameart.org/content/boxy-bold-truetype-font CC0)  
Clint Bellanger

### Images

BG: Background Set (http://opengameart.org/content/background-set CC BY-SA 3.0)  
Dominique Knobben (AquilaSol)  
Original (https://opengameart.org/content/large-nature-background) © 2012-2013  
Julien Jorge (julien.jorge@stuff-o-matic.com)

Credits HUD: Shiny hud (http://opengameart.org/content/shiny-hud CC0)  
Michele Bucelli (Buch)

Cursors: Copyright 2008 (Licensed under CC BY 3.0 https://opengameart.org/content/cursors-arrows-map-markers-ardentryst)  
Elle Trudgett (https://github.com/elle-trudgett)

Defeat: Nuclear Mushroom Cloud (http://opengameart.org/content/nuclear-mushroom-cloud CC0)  
United States Department of Energy

Jeep Button: Svalbard landscape.jpg (http://commons.wikimedia.org/wiki/File:Svalbard_landscape.jpg CC BY 2.0)  
Billy Lindblom

Marine Button: White Plains (http://commons.wikimedia.org/wiki/File:White_Plains.jpg CC BY 2.0)  
Kurt Nordstrom (from Ponder, TX, USA)

Truck Button: Autumn Asphalt Road Landscape Forest Birch Tree (http://pixabay.com/p-218127/?no_redirect CC0)  
PublicDomainPictures

Units: Blender models for Freeciv units (http://opengameart.org/content/blender-models-for-freeciv-units CC0)
yd

Victory: Flickr - Israel Defense Forces - 188th Brigade Training Day, March 2008-cropped.jpg (http://commons.wikimedia.org/wiki/File:Flickr_-_Israel_Defense_Forces_-_188th_Brigade_Training_Day,_March_2008-cropped.jpg CC BY 2.0)  
Matanya

### License Info

CC0 (Creative Commons Zero)  
http://creativecommons.org/publicdomain/zero/1.0/

CC BY 2.0 (Creative Commons Attribution 2.0)  
http://creativecommons.org/licenses/by/2.0/

CC BY 3.0 (Creative Commons Attribution 3.0)  
http://creativecommons.org/licenses/by/3.0/

CC BY-SA 3.0 (Creative Commons Attribution-ShareAlike 3.0)  
http://creativecommons.org/licenses/by-sa/3.0/

CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International)  
http://creativecommons.org/licenses/by-nc-sa/4.0/

GPL 2.0 (GNU General Public License, version 2)  
http://www.gnu.org/licenses/gpl-2.0.html

Thanks to  
ImgBot

---

Code:

```
## Credits

### Code, Design
congusbongus [or perhaps use "full name (nickname)"]

### Audio

Agony: Agony (https://freesound.org/s/162157/ CC0)  
Mediapaja2009

Browning: Air Defense Artillery Avenger Training .50cal (tH4YBTw8vk8).flac (http://freesound.org/s/160355/ CC0)  
Tank Fire: Tank Firing (http://freesound.org/s/168707/ CC0)  
Units (http://opengameart.org/content/sci-fi-rts-war-unit-sounds CC0)  
qubodup

Explode: Various C64 Sid Chip Sound Effects (http://opengameart.org/content/various-c64-sid-chip-sound-effects CC BY-SA 3.0)  
Panayiotis Yianni (Amon)

M16: M-16 automatic gun (http://freesound.org/people/Julien%20Nicolas/sounds/133799/ CC BY 3.0)  
Julien Nicolas

Music: Crystalline Refinement (Into This Wired Abyss Vol. 3) (http://www.ektoplazm.com/free-music/into-this-wired-abyss-vol-3 CC BY-NC-SA 4.0)  
False Identity

Speech: RTS commands and reports (http://opengameart.org/content/rts-commands-and-reports CC0)  
Daniel Stephens (Scribe)

### Font

Boxy Bold Regular 12: Boxy Bold - TrueType Font (http://opengameart.org/content/boxy-bold-truetype-font CC0)  
Clint Bellanger

### Images

BG: Background Set (http://opengameart.org/content/background-set CC BY-SA 3.0)  
Dominique Knobben (AquilaSol)  
Original (https://opengameart.org/content/large-nature-background) © 2012-2013  
Julien Jorge (julien.jorge@stuff-o-matic.com)

Credits HUD: Shiny hud (http://opengameart.org/content/shiny-hud CC0)  
Michele Bucelli (Buch)

Cursors: Copyright 2008 (Licensed under CC BY 3.0 https://opengameart.org/content/cursors-arrows-map-markers-ardentryst)  
Elle Trudgett (https://github.com/elle-trudgett)

Defeat: Nuclear Mushroom Cloud (http://opengameart.org/content/nuclear-mushroom-cloud CC0)  
United States Department of Energy

Jeep Button: Svalbard landscape.jpg (http://commons.wikimedia.org/wiki/File:Svalbard_landscape.jpg CC BY 2.0)  
Billy Lindblom

Marine Button: White Plains (http://commons.wikimedia.org/wiki/File:White_Plains.jpg CC BY 2.0)  
Kurt Nordstrom (from Ponder, TX, USA)

Truck Button: Autumn Asphalt Road Landscape Forest Birch Tree (http://pixabay.com/p-218127/?no_redirect CC0)  
PublicDomainPictures

Units: Blender models for Freeciv units (http://opengameart.org/content/blender-models-for-freeciv-units CC0)
yd

Victory: Flickr - Israel Defense Forces - 188th Brigade Training Day, March 2008-cropped.jpg (http://commons.wikimedia.org/wiki/File:Flickr_-_Israel_Defense_Forces_-_188th_Brigade_Training_Day,_March_2008-cropped.jpg CC BY 2.0)  
Matanya

### License Info

CC0 (Creative Commons Zero)  
http://creativecommons.org/publicdomain/zero/1.0/

CC BY 2.0 (Creative Commons Attribution 2.0)  
http://creativecommons.org/licenses/by/2.0/

CC BY 3.0 (Creative Commons Attribution 3.0)  
http://creativecommons.org/licenses/by/3.0/

CC BY-SA 3.0 (Creative Commons Attribution-ShareAlike 3.0)  
http://creativecommons.org/licenses/by-sa/3.0/

CC BY-NC-SA 4.0 (Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International)  
http://creativecommons.org/licenses/by-nc-sa/4.0/

GPL 2.0 (GNU General Public License, version 2)  
http://www.gnu.org/licenses/gpl-2.0.html

Thanks to  
ImgBot
```

Note: the two spaces at the end of many lines are [needed by markdown for a line break](https://stackoverflow.com/a/47534655/188159).
